### ISSUE TITLE
Library not compiling on Windows

### ISSUE THREAD

**Issue by ChipLeo** [107-systems/107-Arduino-MCP2515#10]
Path not found for Windows

**Comment by per1234** [comment]
Hi @ChipLeo. It will be helpful if you provide some additional information:

When you encounter an error you'll see a button on the right side of the orange bar in the Arduino IDE "Copy error messages" (or the icon that looks like two pieces of paper at the top right corner of the black console window in the Arduino Web Editor). Click that button.

[Paste](https://lifehacker.com/how-to-copy-cut-and-paste-for-beginners-5801525) the error in a message here using [code fencing](https://guides.github.com/features/mastering-markdown/).

**Comment by ChipLeo** [comment]
`In file included from D:\Leo\Documents\Arduino\libraries\107-Arduino-MCP2515\src/ArduinoMCP2515.h:16:0,

Несколько библиотек найдено для "ArduinoMCP2515.h"
                 from D:\Leo\Documents\Arduino\sketch_apr25a\sketch_apr25a.ino:2:

 Используется: D:\Leo\Documents\Arduino\libraries\107-Arduino-MCP2515
D:\Leo\Documents\Arduino\libraries\107-Arduino-MCP2515\src/MCP2515/MCP2515_Io.h:17:10: fatal error: functional: No such file or directory`

but library exist in 
D:\Leo\Documents\Arduino\libraries\107-Arduino-MCP2515

**Comment by per1234** [comment]
You didn't post the important information of which board you are compiling for. I'm guessing it's one of the AVR boards.

**Comment by ChipLeo** [comment]
Arduino: 1.8.12 (Windows 8.1), Плата:"Arduino Uno"

In file included from D:\Leo\Documents\Arduino\libraries\107-Arduino-MCP2515\src/ArduinoMCP2515.h:16:0,

                 from D:\Leo\Documents\Arduino\sketch_apr25a\sketch_apr25a.ino:2:

D:\Leo\Documents\Arduino\libraries\107-Arduino-MCP2515\src/MCP2515/MCP2515_Io.h:17:10: fatal error: functional: No such file or directory

 #include <functional>

          ^~~~~~~~~~~~

compilation terminated.

exit status 1
Ошибка компиляции для платы Arduino Uno.

Этот отчёт будет иметь больше информации с
включенной опцией Файл -> Настройки ->
"Показать подробный вывод во время компиляции"

**Comment by aentinger** [comment]
@ChipLeo you might want to take a look at https://github.com/autowp/arduino-mcp2515 ... it is an excellent library and should be available for AVR.
