### ISSUE TITLE
[Bug Report] Arduino r4 dont work

### ISSUE THREAD

**Issue by sofresh007** [107-systems/107-Arduino-MCP2515#97]
Hi

I cannot get the library to work with the arduino r4 wifi, im using the cansniffer example but nothing shows up in the serial monitor.

my wiring.

MCP2515 INT -----> DigitalPin 2 Arudino
  MCP2515 SCK -----> DigitalPin 13 Arudino
  MCP2515 SI  -----> DigitalPin 11 Arudino
  MCP2515 SO  -----> DigitalPin 12 Arudino
  MCP2515 CS -----> DigitalPin 10 Arudino
  MCP2515 GND -----> PowerPin GND Arudino
  MCP2515 VCC -----> PowerPin 5v Arudino

also changed to 8mhz chrystal and changed the cs pin to 10 and int pin to 2.

Any help appreciated.

best regards.

**Comment by aentinger** [comment]
Well there could be any number of issues but most importantly github issues are not a support forum.
